### PR TITLE
Chore/add docstring

### PR DESCRIPTION
**Pull request by juanjoDiaz**
This includes #88. So, please, merge that first.

### CODE REVIEW

**Comment by adbar** [comment]
I'm done with #88 and will wait for the conflicts to be resolved before moving on.

**Comment by juanjoDiaz** [comment]
Done!

**Comment by adbar** [comment]
That looks great! Ready to merge then?

**Comment by juanjoDiaz** [comment]
Yes, please!

I have a couple of other small PRs ready to go

**Pull request merged**
