### PR TITLE
refactor: rename extensive to greedy

### PR DESCRIPTION
**Pull request by juanjoDiaz**
To be consistent.

I'm still not 100% clear what greedy does, though.
Some docs are needed. As requested in an existing issue.

### CODE REVIEW

**Comment by adbar** [comment]
I already updated the readme but I'll add something a line or two on language detection here, it's still missing as you say.

**Comment by adbar** [comment]
I'd like to push the readme update but cannot push to your repository anymore, is it normal?

**Comment by juanjoDiaz** [comment]
I normally don't allow maintainers to push to me repos (it could lead to password leakage if I put any password in my fork. Not the case).

I gave you permissions now 🙂

**Comment by adbar** [comment]
Strange, I pushed on your branches before, but I understand, thanks for the change.

Is the readme clearer now?

**Comment by juanjoDiaz** [comment]
Yup. All good!

**Pull request merged**
